### ISSUE TITLE
Pythia8 segmenation fault

### ISSUE THREAD

**Issue by eduard322** [SND-LHC/advsndsw#29]
Hi, I faced the problem in the Pythia simulation of the neutrino flux via script 
$ADVSNDSW_ROOT/macro/runPythia8PP.py
. The problem is caused by call of the any method related to the Info class (segmentation fault). In this code the 63th line causes the seg. fault:
processes = generator.info.codesHard()
I tried to call this method on my local machine with the newer version of pythia (pythia v8312) and did work out. So, I guess, it makes sense to update the pythia version of the sndsw.

**Comment by siilieva** [comment]
thanks for reporting @eduard322 
First, this line only dumps the x-secs of hard processes. Do you need it for your current purpose?
I agree we have to find out why it works for v8312 and not for our v8309, or maybe it is another issue with the stack.
@eduard322 , could you try to reproduce using standalone v8309?
@olantwin, I would avoid having separate stacks for sndsw and adsndsw as it will indeed be too much of an effort.

**Comment by olantwin** [comment]
> @olantwin, I would avoid having separate stacks for sndsw and adsndsw as it will indeed be too much of an effort.

Maybe I was unclear, but we completely agree here. I don't want to (and can't) maintain another stack.

**Comment by eduard322** [comment]
Hi @siilieva and @olantwin 
I guess I will need this line as it calculates the luminosity in the end of script, so I assume that this will be important for future documents, reports etc. 
@olantwin, is it possible then to put this stack into one of the snsdw branches?

**Comment by siilieva** [comment]
@eduard322, I have a fix that issue that allows using the generator.info with the current sndsw stack.
Will push it less than hour

**Comment by olantwin** [comment]
> @olantwin, is it possible then to put this stack into one of the snsdw branches?

What stack? I'm also not sure what you mean by putting a stack in an sndsw branch.
